// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.ordina.repository;

import be.ordina.repository.PersonRepository;
import org.springframework.stereotype.Repository;

privileged aspect PersonRepository_Roo_Jpa_Repository {
    
    declare @type: PersonRepository: @Repository;
    
}
